# Generated by Django 2.2 on 2023-05-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0003_auto_20230527_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='export_to_CSV',
        ),
    ]
